apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kubehealer.fullname" . }}-secrets
  labels:
    {{- include "kubehealer.labels" . | nindent 4 }}
type: Opaque
stringData:
  JWT_SECRET: {{ .Values.jwtSecret | quote }}
  NEXTAUTH_SECRET: {{ include "kubehealer.nextAuthSecret" . | quote }}
  DATABASE_URL: {{ include "kubehealer.databaseUrl" . | quote }}
