apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cognix.fullname" . }}-secrets
  labels:
    {{- include "cognix.labels" . | nindent 4 }}
type: Opaque
stringData:
  JWT_SECRET: {{ .Values.jwtSecret | quote }}
  NEXTAUTH_SECRET: {{ include "cognix.nextAuthSecret" . | quote }}
  DATABASE_URL: {{ include "cognix.databaseUrl" . | quote }}
